### ISSUE TITLE
Invalid Child context warning

### ISSUE THREAD

**Issue by aadarshashutosh** [grozafry/LoginToDoApp#6]
'Warning: Failed child context type: Invand child

context virtualizedCell.cellKey of type 'number
supplied to CellRenderer

expected string'

![image](https://user-images.githubusercontent.com/34771316/81053139-41728a00-8ee2-11ea-80a8-8bd8ef77951d.png)

**Comment by grozafry** [comment]
Fixed. I had to add a keyExtractor to the flatlist which returns a key of type 'string' (All keys must be string in newer versions of react-native).
